# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: post/:title
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: domenick-lieneweg.de
baseurl:
title: Domenick Lieneweg
author: Domenick Lieneweg
description: Persoenlicher Blog und Projekt-Verzeichnis
avatar: profile.png
email: mail@domenick-lieneweg.de
github: DomeCode
twitter:

# needed for travis-ci build
exclude: [vendor]
